# Generated by Django 4.0.3 on 2022-09-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_image_user_phone_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='0', max_length=12, unique=True, verbose_name='شماره تلفن'),
        ),
    ]
