# Generated by Django 4.0.3 on 2022-09-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_otp_options_remove_otp_user_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='password',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
