# Generated by Django 4.0.3 on 2022-09-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_otp_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='token',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
